eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090

spring:
  application:
    name: students

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:students}
    username: ${MYSQL_USER:supun}
    password: ${MYSQL_PASSWORD:Arduino@123}

  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/students
  #    username: username
  #    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
